routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::middleware(['auth'])->group(function() {

    Route::get('/', [HomeController::class, 'index'])->name('home');

    Route::name('products.')->prefix('Products')->group(function () {

        Route::get('/', [ProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:products-view');

        Route::get('/create', [ProductController::class,'create'])
            ->name('create')
            ->middleware('permission:products-create');

        Route::post('/store', [ProductController::class,'store'])
            ->name('store')
            ->middleware('permission:products-store');

        Route::get('/show/{id}', [ProductController::class,'find'])
            ->name('find')
            ->middleware('permission:products-find');

        Route::get('/edit/{id}', [ProductController::class,'edit'])
            ->name('edit')
            ->middleware('permission:products-edit');

        Route::patch('/update/{id}', [ProductController::class,'update'])
            ->name('update')
            ->middleware('permission:products-update');

        Route::delete('/delete/{id}', [ProductController::class,'delete'])
            ->name('delete')
            ->middleware('permission:products-delete');

    });

    Route::name('roles.')->prefix('Roles')->group(function () {

        Route::get('/', [RoleController::class,'index'])
            ->name('index')
            ->middleware('permission:roles-view');

        Route::get('/create', [RoleController::class,'create'])
            ->name('create')
            ->middleware('permission:roles-create');

        Route::get('/show/{id}', [RoleController::class,'show'])
            ->name('show')
            ->middleware('permission:roles-show');

        Route::get('/edit/{id}', [RoleController::class,'edit'])
            ->name('edit')
            ->middleware('permission:roles-edit');

        Route::put('/update/{id}', [RoleController::class,'update'])
            ->name('update')
            ->middleware('permission:roles-update');

        Route::delete('/delete/{id}', [RoleController::class,'delete'])
            ->name('delete')
            ->middleware('permission:roles-delete');

        Route::post('/', [RoleController::class,'store'])
            ->name('store')
            ->middleware('permission:roles-store');

    });

    Route::name('users.')->prefix('users')->group(function () {

        Route::get('/', [UserController::class,'index'])
            ->name('index')
            ->middleware('permission:user-view');

        Route::get('/create', [UserController::class,'create'])
            ->name('create')
            ->middleware('permission:user-create');

        Route::post('/store', [UserController::class,'store'])
            ->name('store')
            ->middleware('permission:user-store');

        Route::get('/show/{id}', [UserController::class,'show'])
            ->name('show')
            ->middleware('permission:user-show');

        Route::get('/edit/{id}', [UserController::class,'edit'])
            ->name('edit')
            ->middleware('permission:user-edit');

        Route::put('/update/{id}', [UserController::class,'update'])
            ->name('update')
            ->middleware('permission:user-update');

        Route::delete('/delete/{id}', [UserController::class,'delete'])
            ->name('delete')
            ->middleware('permission:user-delete');

    });
    Route::name('categories.')->prefix('Categories')->group(function () {

        Route::get('/', [CategoryController::class,'index'])
            ->name('index')
            ->middleware('permission:categories-index');

        Route::get('/create', [CategoryController::class,'create'])
            ->name('create')
            ->middleware('permission:categories-create');

        Route::post('/store', [CategoryController::class,'store'])
            ->name('store')
            ->middleware('permission:categories-store');

        Route::get('/show/{id}', [CategoryController::class,'show'])
            ->name('show')
            ->middleware('permission:categories-show');

        Route::get('/edit/{id}', [CategoryController::class,'edit'])
            ->name('edit')
            ->middleware('permission:categories-edit');

        Route::put('/update/{id}', [CategoryController::class,'update'])
            ->name('update')
            ->middleware('permission:categories-update');

        Route::delete('/delete/{id}', [CategoryController::class,'delete'])
            ->name('delete')
            ->middleware('permission:categories-delete');

    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany(
            Role::class,
            'user_role',
            'user_id',
            'role_id'
        );
    }

    public function syncRole(array $roles)
    {
        return $this->roles()->sync($roles);
    }

    public function attachRole(array $roles)
    {
        return $this->roles()->attach($roles);
    }

    public function detachRole()
    {
        return $this->roles()->detach();
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    public function scopeWithRoleId($query, $role)
    {
        return $role ? $query->WhereHas('roles', function ($query) use ($role) {
            $query->where('id', $role);
        }): null;
    }

    public function hasPermission($permission)
    {
        foreach ($this->roles as $role){
            if($role->permissions()->where('name', $permission)->exists()){
                return true;
            }
        }
        return false;
    }

    public function hasRole($role)
    {
        return $this->roles()->where('name_special', $role)->exists();
    }

    public function isSuperAdmin()
    {
        return $this->hasRole('super_admin');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Services\RoleService;
use App\Services\UserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\View;

class UserController extends Controller
{
    protected $roleService;
    protected $userService;

    public function __construct(RoleService $roleService,UserService $userService)
    {
        $this->roleService = $roleService;
        $this->userService = $userService;

        View::share('roles', $this->roleService->all());
    }

    public function index(Request $request)
    {
        $users = $this->userService->search($request);
        return view('users.index',compact('users'));
    }

    public function create()
    {
        return view('users.create');
    }

    public function store(UserRequest $request)
    {
        $this->userService->store($request);
        return redirect()->route('users.index')->with('message', 'Save success');
    }

    public function show($id)
    {
        $user = $this->userService->find($id);
        return view('users.show',compact('user'));
    }

    public function edit($id)
    {
        $user = $this->userService->find($id);
        return view('users.edit',compact('user'));
    }

    public function update(UserRequest $request, $id)
    {
        $this->userService->update($request, $id);
        return redirect()->route('users.index')->with('message', 'Update success');
    }

    public function delete($id)
    {
        $this->userService->delete($id);
        return redirect()->route('users.index')->with('message', 'Delete success');
    }
}

resources/views/users/create.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">User Management</h4>
                        <form action="{{ route('users.store') }}" method="POST" class="form-sample">
                            @csrf
                            <p class="card-description">
                                Personal info
                            </p>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="name" />
                                        </div>
                                    </div>
                                    @error('name')
                                    <div  style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">E-Mail</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="email"/>
                                        </div>
                                    </div>
                                    @error('email')
                                    <div  style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Password</label>
                                        <div class="col-sm-9">
                                            <input type="password" class="form-control" name="password"/>
                                        </div>
                                    </div>
                                    @error('password')
                                    <div style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Roles</label>
                                        <div class="col-sm-9">
                                            <select class="js-example-basic-multiple w-100" multiple="multiple" name="role_id[]">
                                                @foreach($roles as $iterm)
                                                    <option value="{{ $iterm->id }}">{{$iterm->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    @error('role_id')
                                    <div style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="row">
                                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">User Management</h4>
                        <form action="{{route('users.update',$user->id)}}" method="POST" class="form-sample">
                            @csrf
                            @method('PUT')
                            <p class="card-description">
                                Personal info
                            </p>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="name" value="{{ $user->name }}"/>
                                        </div>
                                    </div>
                                    @error('name')
                                    <div  style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">E-Mail</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="email" value="{{ $user->email }}"/>
                                        </div>
                                    </div>
                                    @error('email')
                                    <div  style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Password</label>
                                        <div class="col-sm-9">
                                            <input type="password" class="form-control" name="password"/>
                                        </div>
                                    </div>
                                    @error('password')
                                    <div style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Confirm Password</label>
                                        <div class="col-sm-9">
                                            <input type="password" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <select class="js-example-basic-multiple w-100" multiple="multiple" name="role_id[]">
                                                @foreach($roles as $iterm)
                                                    <option  {{$user->roles->contains('id', $iterm->id) ? 'selected' : ''}} value="{{ $iterm->id }}">{{$iterm->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @error('role_id')
                            <div style="color: red;">{{ $message }}</div>
                            @enderror
                            <div class="row">
                                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">User Management</h4>
                        <a href="{{ route('users.create') }}" class="btn btn-primary">Create user</a>
                        <form action="{{ route('users.index') }}" method="GET">
                            <div class="row">
                                <div class="col-md-3">
                                    <input type="text" class="form-control" name="name" placeholder="name"/>
                                </div>
                                <div class="col-md-3">
                                    <select class="js-example-basic-single w-100" name="role_id">
                                        <option value="">Select Role</option>
                                        @foreach($roles as $iterm)
                                            <option value="{{ $iterm->id }}">{{ $iterm->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <button type="submit" class="btn btn-info">Search</button>
                                </div>
                            </div>
                        </form>
                        <div class="table-responsive pt-3">
                            <p style="display: none;">{{ $stt = 0 }}</p>
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(!empty($users))
                                    @foreach($users as $iterm)
                                        <tr>
                                            <td>{{ $stt = $stt + 1 }}</td>
                                            <td>{{ $iterm->name }}</td>
                                            <td>{{ $iterm->email }}</td>
                                            <form action="{{route('users.delete',$iterm->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <td>
                                                    @hasPermission('user-delete')
                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                    @endhasPermission
                                                    @hasPermission('user-show')
                                                    <a href="{{ route('users.show',$iterm->id) }}" class="btn btn-warning">Detail</a>
                                                    @endhasPermission
                                                    @hasPermission('user-edit')
                                                    <a href="{{ route('users.edit',$iterm->id) }}" class="btn btn-warning">Edit</a>
                                                    @endhasPermission
                                                </td>
                                            </form>
                                        </tr>
                                    @endforeach
                                @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">User Management</h4>
                        <form action="" method="POST" class="form-sample">
                            <p class="card-description">
                                Personal info
                            </p>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="name" value="{{ $user->name }}"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">E-Mail</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="email" value="{{ $user->email }}"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Roles</label>
                                        <div class="col-sm-9">
                                            @foreach($user->roles as $iterm)
                                                <p>{{$iterm->name}}</p>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/update.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">User Management</h4>
                        <form action="{{ route('Users.update',$user->id) }}" method="POST" class="form-sample">
                            @csrf
                            @method('PUT')
                            <p class="card-description">
                                Personal info
                            </p>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="name" value="{{ $user->name }}"/>
                                        </div>
                                    </div>
                                    @error('name')
                                    <div  style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">E-Mail</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="email" value="{{ $user->email }}"/>
                                        </div>
                                    </div>
                                    @error('email')
                                    <div  style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Password</label>
                                        <div class="col-sm-9">
                                            <input type="password" class="form-control" name="password"/>
                                        </div>
                                    </div>
                                    @error('password')
                                    <div  style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Confirm Password</label>
                                        <div class="col-sm-9">
                                            <input type="password" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <select class="js-example-basic-multiple w-100" multiple="multiple" name="roles[]">
                                                @foreach($roles as $iterm)
                                                    <option  {{$user->roles->contains('id', $iterm->id) ? 'selected' : ''}} value="{{ $iterm->id }}">{{$iterm->roles}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection