routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::middleware(['auth'])->group(function() {

    Route::get('/', [HomeController::class, 'index'])->name('home');

    Route::name('products.')->prefix('Products')->group(function () {

        Route::get('/', [ProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:products-view');

        Route::get('/create', [ProductController::class,'create'])
            ->name('create')
            ->middleware('permission:products-create');

        Route::post('/store', [ProductController::class,'store'])
            ->name('store')
            ->middleware('permission:products-store');

        Route::get('/show/{id}', [ProductController::class,'find'])
            ->name('find')
            ->middleware('permission:products-find');

        Route::get('/edit/{id}', [ProductController::class,'edit'])
            ->name('edit')
            ->middleware('permission:products-edit');

        Route::patch('/update/{id}', [ProductController::class,'update'])
            ->name('update')
            ->middleware('permission:products-update');

        Route::delete('/delete/{id}', [ProductController::class,'delete'])
            ->name('delete')
            ->middleware('permission:products-delete');

    });

    Route::name('roles.')->prefix('Roles')->group(function () {

        Route::get('/', [RoleController::class,'index'])
            ->name('index')
            ->middleware('permission:roles-view');

        Route::get('/create', [RoleController::class,'create'])
            ->name('create')
            ->middleware('permission:roles-create');

        Route::get('/show/{id}', [RoleController::class,'show'])
            ->name('show')
            ->middleware('permission:roles-show');

        Route::get('/edit/{id}', [RoleController::class,'edit'])
            ->name('edit')
            ->middleware('permission:roles-edit');

        Route::put('/update/{id}', [RoleController::class,'update'])
            ->name('update')
            ->middleware('permission:roles-update');

        Route::delete('/delete/{id}', [RoleController::class,'delete'])
            ->name('delete')
            ->middleware('permission:roles-delete');

        Route::post('/', [RoleController::class,'store'])
            ->name('store')
            ->middleware('permission:roles-store');

    });

    Route::name('users.')->prefix('users')->group(function () {

        Route::get('/', [UserController::class,'index'])
            ->name('index')
            ->middleware('permission:user-view');

        Route::get('/create', [UserController::class,'create'])
            ->name('create')
            ->middleware('permission:user-create');

        Route::post('/store', [UserController::class,'store'])
            ->name('store')
            ->middleware('permission:user-store');

        Route::get('/show/{id}', [UserController::class,'show'])
            ->name('show')
            ->middleware('permission:user-show');

        Route::get('/edit/{id}', [UserController::class,'edit'])
            ->name('edit')
            ->middleware('permission:user-edit');

        Route::put('/update/{id}', [UserController::class,'update'])
            ->name('update')
            ->middleware('permission:user-update');

        Route::delete('/delete/{id}', [UserController::class,'delete'])
            ->name('delete')
            ->middleware('permission:user-delete');

    });
    Route::name('categories.')->prefix('Categories')->group(function () {

        Route::get('/', [CategoryController::class,'index'])
            ->name('index')
            ->middleware('permission:categories-index');

        Route::get('/create', [CategoryController::class,'create'])
            ->name('create')
            ->middleware('permission:categories-create');

        Route::post('/store', [CategoryController::class,'store'])
            ->name('store')
            ->middleware('permission:categories-store');

        Route::get('/show/{id}', [CategoryController::class,'show'])
            ->name('show')
            ->middleware('permission:categories-show');

        Route::get('/edit/{id}', [CategoryController::class,'edit'])
            ->name('edit')
            ->middleware('permission:categories-edit');

        Route::put('/update/{id}', [CategoryController::class,'update'])
            ->name('update')
            ->middleware('permission:categories-update');

        Route::delete('/delete/{id}', [CategoryController::class,'delete'])
            ->name('delete')
            ->middleware('permission:categories-delete');

    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $table = 'categories';

    protected $fillable = [
        'name',
        'slug',
        'parent_id'
    ];

    public function childrens()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function products()
    {
        return $this->belongsToMany(
            Product::class,
            'product_category',
            'category_id',
            'product_id'
        );
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\View;

class CategoryController extends Controller
{
    protected $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;

        View::share('categories', $this->categoryService->all());
    }

    public function index()
    {
        return view('categories.index');
    }

    public function create()
    {
        return view('categories.create');
    }

    public function store(CategoryRequest $request)
    {
        $this->categoryService->store($request->all());
        return redirect()->route('categories.index')->with('message', 'Save success');
    }

    public function show($id)
    {
        $category = $this->categoryService->find($id);
        return view('categories.show', compact('category'));
    }

    public function edit($id)
    {
        $category = $this->categoryService->find($id);
        $categories = $this->categoryService->all();
        return view('categories.edit', compact('category'));
    }

    public function update(Request $request,$id)
    {
        $this->categoryService->update($request,$id);
        return redirect()->route('categories.index')->with('message', 'Update success');
    }

    public function delete($id)
    {
        $this->categoryService->delete($id);
        return redirect()->route('categories.index')->with('message', 'Delete success');
    }
}

resources/views/categories/create.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Category Management</h4>
                        <form action="{{route('categories.store')}}" method="POST" class="form-sample">
                            @csrf
                            <p class="card-description">
                                Category info
                            </p>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="name" placeholder="Name ..."/>
                                        </div>
                                    </div>
                                    @error('name')
                                    <div  style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Note</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="slug"  placeholder="note.."/>
                                        </div>
                                    </div>
                                    @error('slug')
                                    <div  style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Danh mục</label>
                                        <div class="col-sm-9">
                                            <select class="js-example-basic-multiple w-100" name="parent_id">
                                                <option value="" disabled selected>---chọn danh mục---</option>
                                                @foreach($categories as $iterm)
                                                    <option value="{{ $iterm->id }}">{{ $iterm->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/edit.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Category Management</h4>
                        <form action="{{route('categories.update',$category->id)}}" method="POST" class="form-sample">
                            @csrf
                            @method('PUT')
                            <p class="card-description">
                                Category info
                            </p>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="name" placeholder="Name ..." value="{{$category->name}}"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Slug</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="slug"  placeholder="Slug.." value="{{$category->slug}}"/>
                                        </div>
                                    </div>
                                </div>
                               <div class="col-md-6">
                                   <div class="form-group row">
                                       <label class="col-sm-3 col-form-label">Category</label>
                                       <div class="col-sm-9">
                                           <select class="js-example-basic-multiple w-100" name="parent_id">
                                               <option value="" disabled selected>---chọn danh mục---</option>
                                               @foreach($categories as $iterm)
                                                   <option  {{ $category->parent_id == $iterm->id ? 'selected' : ''}}  value="{{ $iterm->id }}">{{ $iterm->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Catogory Management</h4>
                        <a href="{{ route('categories.create') }}" class="btn btn-primary">Create Catogory</a>
                        <div style="display: none;">{{$stt = 0}}</div>
                        <div class="table-responsive pt-3">
                            <div style="display: none;">{{$stt = 0}}</div>
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Tên danh mục</th>
                                    <th>Danh mục con</th>
                                    <th>Slug</th>
                                    <th>Hành động</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($categories as $category)
                                    <tr>
                                        <td>{{$stt = $stt + 1}}</td>
                                        <td>{{$category->name}}</td>
                                        <td>
                                            @if(count($category->childrens) > 0)
                                                @foreach($category->childrens as $child)
                                                    {{$child->name}},
                                                @endforeach
                                            @endif
                                        </td>
                                        <td>{{$category->slug}}</td>
                                        <form action="{{route('categories.delete',$category->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <td>
                                                @hasPermission('categories-delete')
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                                @endhasPermission
                                                @hasPermission('categories-show')
                                                <a href="{{ route('categories.show',$category->id) }}" class="btn btn-warning">Detail</a>
                                                @endhasPermission
                                                @hasPermission('categories-update')
                                                <a href="{{ route('categories.edit',$category->id) }}" class="btn btn-warning">Edit</a>
                                                @endhasPermission
                                            </td>
                                        </form>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/show.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Category Management</h4>
                        <form action="" >
                            <p class="card-description">
                                Category info
                            </p>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="name" placeholder="Name ..." value="{{$category->name}}"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Slug</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="slug"  placeholder="Slug.." value="{{$category->slug}}"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Danh mục</label>
                                        @foreach($category->products as $iterm)
                                            <span class="label success">{{$iterm->name}}</span>
                                        @endforeach

                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        .label {
            color: white;
            padding: 8px;
            margin: 10px;
        }
        .success {background-color: #04AA6D;} /* Green */
    </style>
@endsection