routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::middleware(['auth'])->group(function() {

    Route::get('/', [HomeController::class, 'index'])->name('home');

    Route::name('products.')->prefix('Products')->group(function () {

        Route::get('/', [ProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:products-view');

        Route::get('/create', [ProductController::class,'create'])
            ->name('create')
            ->middleware('permission:products-create');

        Route::post('/store', [ProductController::class,'store'])
            ->name('store')
            ->middleware('permission:products-store');

        Route::get('/show/{id}', [ProductController::class,'find'])
            ->name('find')
            ->middleware('permission:products-find');

        Route::get('/edit/{id}', [ProductController::class,'edit'])
            ->name('edit')
            ->middleware('permission:products-edit');

        Route::patch('/update/{id}', [ProductController::class,'update'])
            ->name('update')
            ->middleware('permission:products-update');

        Route::delete('/delete/{id}', [ProductController::class,'delete'])
            ->name('delete')
            ->middleware('permission:products-delete');

    });

    Route::name('roles.')->prefix('Roles')->group(function () {

        Route::get('/', [RoleController::class,'index'])
            ->name('index')
            ->middleware('permission:roles-view');

        Route::get('/create', [RoleController::class,'create'])
            ->name('create')
            ->middleware('permission:roles-create');

        Route::get('/show/{id}', [RoleController::class,'show'])
            ->name('show')
            ->middleware('permission:roles-show');

        Route::get('/edit/{id}', [RoleController::class,'edit'])
            ->name('edit')
            ->middleware('permission:roles-edit');

        Route::put('/update/{id}', [RoleController::class,'update'])
            ->name('update')
            ->middleware('permission:roles-update');

        Route::delete('/delete/{id}', [RoleController::class,'delete'])
            ->name('delete')
            ->middleware('permission:roles-delete');

        Route::post('/', [RoleController::class,'store'])
            ->name('store')
            ->middleware('permission:roles-store');

    });

    Route::name('users.')->prefix('users')->group(function () {

        Route::get('/', [UserController::class,'index'])
            ->name('index')
            ->middleware('permission:user-view');

        Route::get('/create', [UserController::class,'create'])
            ->name('create')
            ->middleware('permission:user-create');

        Route::post('/store', [UserController::class,'store'])
            ->name('store')
            ->middleware('permission:user-store');

        Route::get('/show/{id}', [UserController::class,'show'])
            ->name('show')
            ->middleware('permission:user-show');

        Route::get('/edit/{id}', [UserController::class,'edit'])
            ->name('edit')
            ->middleware('permission:user-edit');

        Route::put('/update/{id}', [UserController::class,'update'])
            ->name('update')
            ->middleware('permission:user-update');

        Route::delete('/delete/{id}', [UserController::class,'delete'])
            ->name('delete')
            ->middleware('permission:user-delete');

    });
    Route::name('categories.')->prefix('Categories')->group(function () {

        Route::get('/', [CategoryController::class,'index'])
            ->name('index')
            ->middleware('permission:categories-index');

        Route::get('/create', [CategoryController::class,'create'])
            ->name('create')
            ->middleware('permission:categories-create');

        Route::post('/store', [CategoryController::class,'store'])
            ->name('store')
            ->middleware('permission:categories-store');

        Route::get('/show/{id}', [CategoryController::class,'show'])
            ->name('show')
            ->middleware('permission:categories-show');

        Route::get('/edit/{id}', [CategoryController::class,'edit'])
            ->name('edit')
            ->middleware('permission:categories-edit');

        Route::put('/update/{id}', [CategoryController::class,'update'])
            ->name('update')
            ->middleware('permission:categories-update');

        Route::delete('/delete/{id}', [CategoryController::class,'delete'])
            ->name('delete')
            ->middleware('permission:categories-delete');

    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $table = "products";
    protected $fillable = ['name','image','price'];


    public function categories()
    {
        return $this->belongsToMany(
            Category::class,
            'product_category',
            'product_id',
            'category_id'
        );
    }

    public function addCategories($categoryIds)
    {
        return $this->categories()->attach($categoryIds);
    }

    public function syncCategories($categoryIds)
    {
        return $this->categories()->sync($categoryIds);
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%'.$name.'%') : null;
    }

    public function scopeWithCategoryName($query, $name)
    {
        return $name ? $query->WhereHas('categories', function ($query) use ($name) {
            $query->where('name', $name);
        }): null;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\CreateProductRequest;
use App\Http\Requests\ProductRequest;
use App\Http\Requests\ProductUpdateRequest;
use App\Http\Resources\ProductResource;
use App\Services\CategoryService;
use App\Services\ProductService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\View;
use Intervention\Image\Facades\Image;

class ProductController extends Controller
{
    protected $categoryservice;

    public function __construct(CategoryService $categoryservice,ProductService $productService)
    {
        $this->categoryservice = $categoryservice;
        $this->productService = $productService;

        View::share('categories', $this->categoryservice->all());
    }

    public function index(Request $request)
    {
        $products = $this->productService->search($request);
        return view('products.index',compact('products'));
    }

    public function create()
    {
        return view('products.create');
    }

    public function list()
    {
        $products = $this->productService->all();
        return view('products.table',compact('products'));
    }

    public function store(ProductRequest $request)
    {
        $this->productService->create($request);
        $productList = $this->list();
        return $productList;
    }

    public function find($id)
    {
        $product = $this->productService->find($id);
        return view('products.show',compact('product'));
    }

    public function edit($id)
    {
        $product = $this->productService->find($id);
        return view('products.edit',compact('product'));
    }

    public function update(ProductUpdateRequest $request,$id)
    {
        $this->productService->update($request,$id);
        $productList = $this->list();
        return $productList;
    }

    public function delete($id)
    {
        $this->productService->delete($id);
        $productList = $this->list();
        return $productList;
    }
}

resources/views/products/create.blade.php
<form id="form-create">
    <div class="modal-body">
        <div class="form-group">
            <input type="text" class="form-control" name="name"  placeholder="name">
        </div>
        <div class="error" id="error-name"></div>
        <div class="form-group">
            <input type="text" class="form-control" id="price" name="price"  placeholder="price">
        </div>
        <div class="error" id="error-price"></div>
        <div class="form-group">
            @foreach($categories as $iterm)
                <div>
                    <input type="checkbox" name="categories[]" value="{{$iterm->id}}">
                    <label>{{$iterm->name}}</label>
                </div>
            @endforeach
        </div>
        <div class="error" id="error-categories"></div>
        <div class="form-group">
            <input type="file"  class="form-control" name="image">
        </div>
        <div class="error" id="error-image"></div>
    </div>

    <div id="error-name"></div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="add-product" data-url="{{ route('products.store') }}">Create</button>
    </div>
</form>

resources/views/products/edit.blade.php
{{--  Modal form update  --}}
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Add Product</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form id="form-update">
    <div class="modal-body">
        <div class="form-group">
            <input type="text" class="form-control" id="nameUpdate" name="name" value="{{$product->name}}">
        </div>
        <div class="error" id="error-name"></div>
        <div class="form-group">
            <input type="text" class="form-control" id="name" name="price"  placeholder="price" value="{{$product->price}}">
        </div>
        <div class="error" id="error-price"></div>
        <div class="form-group">
            @foreach($categories as $iterm)
                <div>
                    <input {{$product->categories->contains('id', $iterm->id) ? 'checked' : ''}}
                           type="checkbox" name="categories[]" value="{{$iterm->id}}">
                    <label>{{$iterm->name}}</label>
                </div>
            @endforeach
        </div>
        <div class="error" id="error-categories"></div>
        <div class="form-group">
            <input type="file"  class="form-control" name="image" id="imageUpdate">
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success" router-update-url="{{route('products.update',$product->id)}}" id="update-product" name="updateId" value="{{$product->id}}">Update</button>
    </div>
</form>

resources/views/products/index.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <h4 class="card-title">Product Management</h4>
                        </div>
                        <div class="row">
                            @hasPermission('products-store')
                            <button type="button" class="btn btn-success" data-toggle="modal" id="create-modal-view" data-url-create="{{route('products.create')}}">
                                <i class="fa fa-fw fa-edit"></i>
                                Thêm Sản phẩm
                            </button>
                            @endhasPermission
                        </div>
                        <br>
                        <form action="{{route('products.index')}}" method="GET">
                            <div class="row">
                                <div class="col-md-4">
                                    <input type="text" class="form-control" placeholder="Name" name="namesearch">
                                </div>
                                <div class="col-md-4">
                                    <input type="text" class="form-control" placeholder="Category" name="categorysearch">
                                </div>
                                <div class="col-md-4">
                                    <button type="submit" class="btn btn-primary">Tìm kiếm</button>
                                </div>
                            </div>
                        </form>
                        <div class="table-responsive pt-3">
                            <div style="display: none;">{{$stt = 0}}</div>
                            <table class="table table-bordered" id="product-table">
                                <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Tên sản phẩm</th>
                                        <th>Ảnh mô tả</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody >
                                    @foreach($products as $product)
                                        <tr>
                                            <th>{{ $stt=$stt+1 }}</th>
                                            <th>{{ $product->name }}</th>
                                            <th>
                                                <img src="{{ asset('uploads/products/'.$product->image) }}"  width="50px"alt="">
                                            </th>
                                            <th>
                                                @hasPermission('products-find')
                                                <button type="button" class="btn btn-success show-modal-product"  value="{{$product->id}}" data-url-find="{{route('products.find',$product->id)}}">Show</button>
                                                @endhasPermission
                                                @hasPermission('products-delete')
                                                <button type="button" class="btn btn-danger delete-modal-product" value="{{$product->id}}" data-url-delete="{{route('products.delete',$product->id)}}" >Delete</button>
                                                @endhasPermission
                                                @hasPermission('products-edit')
                                                <button type="button" class="btn btn-success edit-modal-product"  value="{{$product->id}}" data-url-find="{{route('products.edit',$product->id)}}">Update</button>
                                                @endhasPermission
                                            </th>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{--  Modal form add  --}}
    <div class="modal fade" id="createProductModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add Product</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="append-html-create">

                </div>
            </div>
        </div>
    </div>


    {{--  Modal form show  --}}
    <div class="modal fade" id="showProductModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="show-product">

            </div>
        </div>
    </div>


    {{--  Modal form update  --}}
    <div class="modal" id="updateProductModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="update-product-view">

            </div>
        </div>
    </div>

    {{--  Modal form delete  --}}
    <div class="modal" id="deleteProductModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form id="form-delete">
                    <div class="modal-header">
                        <h5 class="modal-title">Xóa sản phẩm</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Bạn chắc chắn muốn xóa không?</p>
                    </div>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="delete-product">Delete</button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="module" src="{{asset('js/product.js')}}"></script>

    <style>
        .error{
            color: red;
        }
    </style>
@endsection

resources/views/products/show.blade.php
<script src="{{asset('css/Layouts/Admin/vendors/select2/select2.min.js')}}"></script>
{{--  Modal form update  --}}
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Product</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <form>
        <div class="modal-body">
            <div class="form-group">
                <input type="text" class="form-control" id="nameUpdate" name="name" value="{{$product->name}}">
            </div>
            <div class="form-group">
                @foreach($categories as $iterm)
                    <div>
                        <input {{$product->categories->contains('id', $iterm->id) ? 'checked' : ''}}
                               type="checkbox" name="categories[]" value="{{$iterm->id}}">
                        <label>{{$iterm->name}}</label>
                    </div>
                @endforeach
            </div>
            <div class="form-group">
                <input type="file"  class="form-control" name="image" id="imageUpdate" value="{{$product->image}}">
            </div>
            <img src="{{ asset('uploads/products/'.$product->image) }}"  width="100px"alt="">
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
    </form>

resources/views/products/table.blade.php
<div style="display: none;">{{$stt = 0}}</div>
<thead>
<tr>
    <th>No.</th>
    <th>Tên sản phẩm</th>
    <th>Ảnh mô tả</th>
    <th></th>
</tr>
</thead>
<tbody >
@foreach($products as $product)
    <tr>
        <th>{{ $stt=$stt+1 }}</th>
        <th>{{ $product->name }}</th>
        <th>
            <img src="{{ asset('uploads/products/'.$product->image) }}"  width="50px" alt="">
        </th>
        <th>
            @hasPermission('products-find')
            <button type="button" class="btn btn-success show-modal-product"  value="{{$product->id}}" data-url-find="{{route('products.find',$product->id)}}">Show</button>
            @endhasPermission
            @hasPermission('products-delete')
            <button type="button" class="btn btn-danger delete-modal-product" value="{{$product->id}}" data-url-delete="{{route('products.delete',$product->id)}}" >Delete</button>
            @endhasPermission
            @hasPermission('products-edit')
            <button type="button" class="btn btn-success edit-modal-product"  value="{{$product->id}}" data-url-find="{{route('products.edit',$product->id)}}">Update</button>
            @endhasPermission</th>
    </tr>
@endforeach
</tbody>