routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::middleware(['auth'])->group(function() {

    Route::get('/', [HomeController::class, 'index'])->name('home');

    Route::name('products.')->prefix('Products')->group(function () {

        Route::get('/', [ProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:products-view');

        Route::get('/create', [ProductController::class,'create'])
            ->name('create')
            ->middleware('permission:products-create');

        Route::post('/store', [ProductController::class,'store'])
            ->name('store')
            ->middleware('permission:products-store');

        Route::get('/show/{id}', [ProductController::class,'find'])
            ->name('find')
            ->middleware('permission:products-find');

        Route::get('/edit/{id}', [ProductController::class,'edit'])
            ->name('edit')
            ->middleware('permission:products-edit');

        Route::patch('/update/{id}', [ProductController::class,'update'])
            ->name('update')
            ->middleware('permission:products-update');

        Route::delete('/delete/{id}', [ProductController::class,'delete'])
            ->name('delete')
            ->middleware('permission:products-delete');

    });

    Route::name('roles.')->prefix('Roles')->group(function () {

        Route::get('/', [RoleController::class,'index'])
            ->name('index')
            ->middleware('permission:roles-view');

        Route::get('/create', [RoleController::class,'create'])
            ->name('create')
            ->middleware('permission:roles-create');

        Route::get('/show/{id}', [RoleController::class,'show'])
            ->name('show')
            ->middleware('permission:roles-show');

        Route::get('/edit/{id}', [RoleController::class,'edit'])
            ->name('edit')
            ->middleware('permission:roles-edit');

        Route::put('/update/{id}', [RoleController::class,'update'])
            ->name('update')
            ->middleware('permission:roles-update');

        Route::delete('/delete/{id}', [RoleController::class,'delete'])
            ->name('delete')
            ->middleware('permission:roles-delete');

        Route::post('/', [RoleController::class,'store'])
            ->name('store')
            ->middleware('permission:roles-store');

    });

    Route::name('users.')->prefix('users')->group(function () {

        Route::get('/', [UserController::class,'index'])
            ->name('index')
            ->middleware('permission:user-view');

        Route::get('/create', [UserController::class,'create'])
            ->name('create')
            ->middleware('permission:user-create');

        Route::post('/store', [UserController::class,'store'])
            ->name('store')
            ->middleware('permission:user-store');

        Route::get('/show/{id}', [UserController::class,'show'])
            ->name('show')
            ->middleware('permission:user-show');

        Route::get('/edit/{id}', [UserController::class,'edit'])
            ->name('edit')
            ->middleware('permission:user-edit');

        Route::put('/update/{id}', [UserController::class,'update'])
            ->name('update')
            ->middleware('permission:user-update');

        Route::delete('/delete/{id}', [UserController::class,'delete'])
            ->name('delete')
            ->middleware('permission:user-delete');

    });
    Route::name('categories.')->prefix('Categories')->group(function () {

        Route::get('/', [CategoryController::class,'index'])
            ->name('index')
            ->middleware('permission:categories-index');

        Route::get('/create', [CategoryController::class,'create'])
            ->name('create')
            ->middleware('permission:categories-create');

        Route::post('/store', [CategoryController::class,'store'])
            ->name('store')
            ->middleware('permission:categories-store');

        Route::get('/show/{id}', [CategoryController::class,'show'])
            ->name('show')
            ->middleware('permission:categories-show');

        Route::get('/edit/{id}', [CategoryController::class,'edit'])
            ->name('edit')
            ->middleware('permission:categories-edit');

        Route::put('/update/{id}', [CategoryController::class,'update'])
            ->name('update')
            ->middleware('permission:categories-update');

        Route::delete('/delete/{id}', [CategoryController::class,'delete'])
            ->name('delete')
            ->middleware('permission:categories-delete');

    });
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    protected $table = 'roles';

    protected $fillable = [
        'name','name_special'
    ];

    public function permissions()
    {
        return $this->belongsToMany(
            Permission::class,
            'role_permission',
            'role_id',
            'permission_id');
    }

    public function attachPermision($permissionId)
    {
        return $this->permissions()->attach($permissionId);
    }

    public function dettachPermision()
    {
        return $this->permissions()->detach();
    }

    public function syncPermision($permissionId)
    {
        return $this->permissions()->sync($permissionId);
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RoleRequest;
use App\Services\PermissionService;
use App\Services\RoleService;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    protected $permissionService;
    protected $roleService;

    public function __construct(PermissionService $permissionService,RoleService $roleService)
    {
        $this->permissionService = $permissionService;
        $this->roleService = $roleService;
    }

    public function index()
    {
        $roles = $this->roleService->all();
        return view('roles.index',compact('roles'));
    }

    public function create()
    {
        $permissions = $this->permissionService->all();
        return view('roles.create',compact('permissions'));
    }

    public function store(RoleRequest $request)
    {
        $this->roleService->store($request);
        return redirect()->route('roles.index')->with('message', 'Save success');
    }

    public function show($id)
    {
        $role = $this->roleService->find($id);
        return view('roles.show',compact('role'));
    }

    public function edit($id)
    {
        $role = $this->roleService->find($id);
        $permissions = $this->permissionService->all();
        return view('roles.edit',compact('role','permissions'));
    }

    public function update(RoleRequest $request,$id)
    {
        $this->roleService->update($request,$id);
        return redirect()->route('roles.index')->with('message', 'Update success');
    }

    public function delete($id)
    {
        $this->roleService->delete($id);
        return redirect()->route('roles.index')->with('message', 'Delete success');
    }
}

resources/views/roles/create.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Role Management</h4>
                        <form action="{{route('roles.store')}}" method="POST" class="form-sample">
                            @csrf
                            <p class="card-description">
                                Personal info
                            </p>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="name" />
                                        </div>
                                    </div>
                                    @error('name')
                                    <div  style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Permission</label>
                                        <div class="col-sm-9">
                                            <select class="js-example-basic-multiple w-100" multiple="multiple" name="permissions[]">
                                                @foreach($permissions as $iterm)
                                                    <option value="{{ $iterm->id }}">{{ $iterm->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/roles/edit.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Role Management</h4>
                        <form action="{{route('roles.update',$role->id)}}" method="POST" class="form-sample">
                            @csrf
                            @method('PUT')
                            <p class="card-description">
                                Personal info
                            </p>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="name" value="{{ $role->name }}"/>
                                        </div>
                                    </div>
                                    @error('name')
                                    <div  style="color: red;">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Permission</label>
                                        <div class="col-sm-9">
                                            <select class="js-example-basic-multiple w-100" multiple="multiple" name="permissions[]">
                                                @foreach($permissions as $iterm)
                                                    <option   {{ $role->permissions->contains('id', $iterm->id) ? 'selected' : ''}}  value="{{ $iterm->id }}">{{ $iterm->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/roles/index.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Roles Management</h4>
                        <div class="table-responsive pt-3">
                            <a href="{{ route('roles.create') }}" class="btn btn-primary">Create role</a>
                            <div style="display: none;">{{$stt = 0}}</div>
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Roles</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($roles as $key => $iterm)
                                    <tr>
                                        <th scope="col">{{ $stt = $stt + 1  }}</th>
                                        <th scope="col">{{ $iterm->name  }}</th>
                                        <th scope="col">
                                            <form method="POST" action="{{route('roles.delete',$iterm->id)}}">
                                                @csrf
                                                @method('DELETE')
                                                @hasPermission('roles-edit')
                                                <a href="{{ route('roles.edit',$iterm->id) }}" class="btn btn-warning" target="_blank">Edit</a>
                                                @endhasPermission
                                                @hasPermission('roles-show')
                                                <a href="{{ route('roles.show',$iterm->id) }}" class="btn btn-warning" target="_blank">Detail</a>
                                                @endhasPermission
                                                @hasPermission('roles-delete')
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                                @endhasPermission
                                            </form>
                                        </th>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/roles/show.blade.php
@extends('Layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Role Management</h4>
                        <form action="" method="POST" class="form-sample">
                            <p class="card-description">
                                Personal info
                            </p>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="name" value="{{ $role->name }}"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Permission</label>
                                        <div class="col-sm-9">
                                            @foreach($role->permissions as $iterm)
                                                <p>{{$iterm->name}}</p>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection